# Generated by Django 3.2.16 on 2022-11-23 16:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('date_time', models.DateTimeField(verbose_name='Время и день доставки')),
                ('delivcomment', models.TextField(blank=True, verbose_name='Комментарий к доставке')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.CharField(choices=[('1', '1'), ('2', '2'), ('2', '3')], max_length=2, verbose_name='Уровни')),
                ('form', models.CharField(choices=[('1', 'Круг'), ('2', 'Квадрат'), ('3', 'Прямоугольник')], max_length=15, verbose_name='Форма')),
                ('topping', models.CharField(choices=[('1', 'Без'), ('2', 'Белый соус'), ('3', 'Карамельный'), ('4', 'Кленовый'), ('5', 'Черничный'), ('6', 'Молочный шоколад'), ('7', 'Клубничный')], max_length=20, verbose_name='Топпинг')),
                ('berries', models.CharField(blank=True, choices=[('1', 'Ежевика'), ('2', 'Малина'), ('3', 'Голубика'), ('4', 'Клубника')], max_length=10, verbose_name='Ягоды')),
                ('decor', models.CharField(blank=True, choices=[('1', 'Фисташки'), ('2', 'Безе'), ('3', 'Фундук'), ('4', 'Пекан'), ('5', 'Маршмеллоу'), ('6', 'Марципан')], max_length=15, verbose_name='Декор')),
                ('words', models.CharField(blank=True, max_length=100, verbose_name='Надпись на торте')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake', to='bakery.order', verbose_name='Заказ')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bakery.user', verbose_name='Пользователь совершивший заказ'),
        ),
    ]
