# Generated by Django 3.2.16 on 2022-11-24 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_auto_20221124_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivcomment',
            new_name='delivcomments',
        ),
        migrations.AddField(
            model_name='ordercake',
            name='cost',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость торта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercake',
            name='levels',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2, verbose_name='Уровни'),
        ),
    ]
