# Generated by Django 3.2.16 on 2022-11-25 09:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_auto_20221124_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='ordercake',
            options={'verbose_name': 'торт', 'verbose_name_plural': 'торты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='ordercake',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='bakery.order', verbose_name='Заказ'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 11, 25, 9, 25, 0, 542481, tzinfo=utc), verbose_name='Создан в')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает оплаты'), ('succeeded', 'Оплачен'), ('canceled', 'Платеж отклонен')], db_index=True, default='waiting', max_length=20, verbose_name='Статус заказа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='bakery.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
            },
        ),
    ]
