# Generated by Django 3.2.16 on 2022-11-25 10:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_auto_20221125_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='ID платежа Юкасса'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 10, 28, 32, 199367, tzinfo=utc), verbose_name='Создан в'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидает оплаты'), ('succeeded', 'Оплачен'), ('canceled', 'Платеж отклонен')], db_index=True, default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
